version: '3'

services:
  web:
    image: 'shutovna/topfive'
    container_name: 'topfive-web'
    ports:
      - 8080:8080
  postgres:
    image: 'postgres'
    container_name: 'topfive-db'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=topfive'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGaRES_DB=topfive'